name: Cortex Code Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cortex-code-scan:
    runs-on: ubuntu-latest   # You can change back to 'sharednp2' if that’s your runner label
    env:
      CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY }}
      CORTEX_API_KEY_ID: ${{ secrets.CORTEX_API_KEY_ID }}
      CORTEX_API_URL: https://api-us.xdr.paloaltonetworks.com   # ✅ Change this if your region differs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Verify Node.js Version
        run: node -v

      - name: Debug environment variables (no secrets shown)
        run: |
          echo "Using Cortex API URL: $CORTEX_API_URL"
          echo "Using Cortex API Key ID: ${CORTEX_API_KEY_ID:0:4}****"

      - name: Download Cortex CLI
        run: |
          set -euo pipefail
          echo "Requesting Cortex CLI download link..."
          crtx_resp=$(curl -sS "${CORTEX_API_URL}/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
            -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" \
            -H "Authorization: ${CORTEX_API_KEY}")
          
          echo "Response: $crtx_resp"
          crtx_url=$(echo "$crtx_resp" | jq -r ".reply.signed_url")

          if [ -z "$crtx_url" ] || [ "$crtx_url" = "null" ]; then
            echo "Failed to obtain signed URL from Cortex API."
            exit 1
          fi

          echo "Downloading Cortex CLI from: $crtx_url"
          curl -sSL -o cortexcli "$crtx_url"
          chmod +x cortexcli
          ./cortexcli --version

      - name: Run Cortex CLI Code Scan
        run: |
          set -euo pipefail
          ./cortexcli \
            --api-base-url "$CORTEX_API_URL" \
            --api-key "$CORTEX_API_KEY" \
            --api-key-id "$CORTEX_API_KEY_ID" \
            code scan \
            --directory "${{ github.workspace }}" \
            --repo-id "${{ github.repository }}" \
            --branch "${{ github.ref_name }}" \
            --source "GITHUB_ACTIONS" \
            --create-repo-if-missing
